name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 0.0.1-dev.8
homepage: "https://supabase.io"
repository: "https://github.com/supabase/supabase-dart"

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  gotrue: ^0.0.1-dev.7
  postgrest: ^0.0.6
  realtime_client: ^0.0.7

dev_dependencies:
  test: ^1.15.4
  lint: ^1.3.0
